/// Generated by Flutter GetX Starter on 2022-04-22 22:00
import 'package:get/get.dart';

import '../logics/categories_logic.dart';

class CategoriesBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<CategoriesLogic>(
      () => CategoriesLogic(),
    );
  }
}