/// Generated by Flutter GetX Starter on 2022-04-11 22:15
import 'package:get/get.dart';

import '../logics/home_logic.dart';

class HomeBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<HomeLogic>(
      () => HomeLogic(),
    );
  }
}