/// Generated by Flutter GetX Starter on 2022-04-25 20:54
import 'package:get/get.dart';

import '../logics/post_detail_logic.dart';

class PostDetailBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<PostDetailLogic>(
      () => PostDetailLogic(),
    );
  }
}