name: news
description: shahrekord news
publish_to: none
version: 1.0.0+1
environment: { sdk: '>=2.16.1 <3.0.0' }
dependencies:
  flutter: { sdk: flutter }
  cupertino_icons: ^1.0.2
  flutter_localizations: { sdk: flutter }
  flutter_html:
  google_fonts:
  get:
  #get_storage: null
  dio:
  fluttertoast:
  flutter_screenutil:
  flutter_svg:
dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints:
flutter:
  uses-material-design: true
  assets: [assets/fonts/, assets/image/]
  fonts:
    - fonts:
        - {asset: assets/fonts/Vazir-Light-UI.ttf}
      family: Vazir
#    - fonts:
#        - {asset: assets/fonts/Vazir-Bold-FD-UI.ttf}
#      family: Vazir
#    - fonts:
#        - {asset: assets/fonts/Vazir-Light-FD-UI.ttf}
#      family: Vazir
