/// Generated by Flutter GetX Starter on 2022-04-15 19:42
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:news/logics/home_logic.dart';
import 'package:news/pages/home/components/latest_news.dart';
import 'package:news/util/request_status.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final HomeLogic logic = Get.put(HomeLogic());

/*  @override
  void dispose() {
    Get.delete<HomeLogic>();
    super.dispose();
  }*/

  @override
  Widget build(BuildContext context) {

    if(logic.postsList.isEmpty) logic.getPost();
    return Obx(() {
      return logic.status.value == RequestStatus.LOADING
          ? const Center(
              child: CircularProgressIndicator(),
            )
          : logic.status.value == RequestStatus.ERROR
              ? Center(
          child: Column(
            children: [
              IconButton(
                  onPressed: () {
                    logic.getPost();                    },
                  icon: const Icon(
                    Icons.refresh,
                    color: Colors.black,
                  )),
              Text(logic.errorMessage.value,
                  style: Theme.of(context).textTheme.subtitle1)
            ],
          ))
              :logic.postsList.isEmpty?Center(
          child: Text("محتوایی برای این صفحه موجود نیست!",
              style: Theme.of(context).textTheme.subtitle1)): Container(
                  child: SingleChildScrollView(child: LatestNews(latest: logic.postsList.value,)),
                );
    });
  }
}
