/// Generated by Flutter GetX Starter on 2022-04-11 22:13

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get_navigation/get_navigation.dart';
import 'package:news/home/home_binding.dart';
import 'package:news/home/home_page.dart';
import 'package:news/util/app_pages.dart';
import 'package:news/util/rout_name.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      //GetMaterialApp from GetX
      textDirection: TextDirection.rtl,
      debugShowCheckedModeBanner: false,
      title: 'Entekhab Supervision App',
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('fa', ''), // Persian, no country code
      ],
      theme: ThemeData(
          scaffoldBackgroundColor: Colors.white,
          primaryColor: Colors.grey,
          fontFamily: "Vazir",
          brightness: Brightness.light),
      home: const HomePage(),
      /*     storage.isLogin ? const ShopBasePage()
          : const AuthBasePage(
        page: Login(),
      ),*/

      initialBinding: HomeBinding(),
      initialRoute: "/",
      getPages: AppPages.pages,
    );
  }

}