/// Generated by Flutter GetX Starter on 2022-04-22 22:00
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:news/pages/categories/components/category_items.dart';
import 'package:news/util/request_status.dart';

import '../../logics/categories_logic.dart';

class CategoriesPage extends StatefulWidget {
  const CategoriesPage({Key? key}) : super(key: key);

  @override
  _CategoriesPageState createState() => _CategoriesPageState();
}

class _CategoriesPageState extends State<CategoriesPage> {
  final CategoriesLogic logic = Get.put(CategoriesLogic());

  @override
  Widget build(BuildContext context) {


    if(logic.categoriesList.isEmpty) logic.getCategories();

    return Obx(() {
      return logic.status.value == RequestStatus.LOADING
          ? const Center(
        child: CircularProgressIndicator(),
      )
          : logic.status.value == RequestStatus.ERROR
          ? Center(
              child: Column(
                children: [
                  IconButton(
                      onPressed: () {
                        logic.getCategories();                    },
                      icon: const Icon(
                        Icons.refresh,
                        color: Colors.black,
                      )),
                  Text(logic.errorMessage.value,
                      style: Theme.of(context).textTheme.subtitle1)
                ],
              ))
          : Container(
        child: GridView.custom(
            padding: EdgeInsets.all(10.0),
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              childAspectRatio: (2 / 1),
              crossAxisSpacing: 10,
              mainAxisSpacing: 10,
            ),
            childrenDelegate: SliverChildListDelegate(
              logic.categoriesList.value.map(
                      (data) => CategoryItem(categoriesModel: data)
              ).toList(),
            )));

    });
  }
}