/// Generated by Flutter GetX Starter on 2022-04-11 22:15
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:news/home/components/bottom_navigation.dart';

import '../logics/home_logic.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final HomeLogic logic = Get.put(HomeLogic());

  static const TextStyle optionStyle =
  TextStyle(fontSize: 30, fontWeight: FontWeight.bold);


  @override
  void dispose() {
    Get.delete<HomeLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.purple,
          centerTitle: true,
          title: const Text("خبر من"),
        ),
        bottomNavigationBar:  BottomNavigation(),
        drawer: const Drawer(),
        body:_widgetOptions[logic.selectedIndex.value],);
    });
  }

  static const List<Widget> _widgetOptions = <Widget>[
    Text(
      'Index 0: Home',
      style: optionStyle,
    ),
    Text(
      'Index 1: Business',
      style: optionStyle,
    ),
    Text(
      'Index 2: School',
      style: optionStyle,
    ),
  ];


}
