/// Generated by Flutter GetX Starter on 2022-04-11 22:15
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:news/logics/container_logic.dart';
import 'package:news/pages/categories/categories_page.dart';
import 'package:news/pages/container/components/bottom_navigation.dart';
import 'package:news/pages/home/home_page.dart';


class ContainerPage extends StatefulWidget {
  const ContainerPage({Key? key}) : super(key: key);

  @override
  _ContainerPageState createState() => _ContainerPageState();
}

class _ContainerPageState extends State<ContainerPage> {
  final ContainerLogic logic = Get.put(ContainerLogic());

  static const TextStyle optionStyle =
  TextStyle(fontSize: 30, fontWeight: FontWeight.bold);


  @override
  void dispose() {
    Get.delete<ContainerLogic>();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.purple,
          centerTitle: true,
          title: const Text("خبر من"),
        ),
        bottomNavigationBar: BottomNavigation(),
        drawer: const Drawer(),
        body: _pages[logic.selectedIndex.value],);
    });
  }

  static  final List<Widget> _pages = <Widget>[

   HomePage()
    ,
   const CategoriesPage(),
    const Text(
      'Index 2: School',
      style: optionStyle,
    ),
  ];


}
