/// Generated by Flutter GetX Starter on 2022-04-11 22:15
import 'package:dio/dio.dart';
import 'package:get/get.dart';
import 'package:news/models/post_model.dart';


class ContainerLogic extends GetxController {
  late Dio dio;
  var selectedIndex = 0.obs;
  var postsList = <PostModel>[].obs;
  @override
  void onInit() {
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }


}
