/// Generated by Flutter GetX Starter on 2022-04-15 19:42
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:news/models/post_model.dart';
import 'package:news/providers/categories_provider.dart';
import 'package:news/providers/post_provider.dart';
import 'package:news/util/error_message.dart';
import 'package:news/util/request_status.dart';


class HomeLogic extends GetxController {
  var postsList = <PostModel>[].obs;
  var postsOfCategoryList = <PostModel>[].obs;
  var status = RequestStatus.INITIALIZE.obs;
  var errorMessage = "".obs;
  var page = 1.obs;

  final ScrollController _controller = ScrollController();

  @override
  void onInit() {

    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }

  getPost() {
    status.value = RequestStatus.LOADING;
    PostProvider().getPosts(
        beforeSend: () {},
        onSuccess: (data) {

          if (data.statusCode == 200) {

            List responseBody = data.data;
            postsList.value =  responseBody.map((e) => PostModel.fromJson(e)).toList();
            status.value = RequestStatus.LOADED;

          } else {
            status.value = RequestStatus.ERROR;
            errorMessage.value = data.statusMessage!;
           // ErrorMessage().show(data.statusMessage!, data.statusCode!);
          }
        },
        onError: (error, code) {
          status.value = RequestStatus.ERROR;
          errorMessage.value = error;

         // ErrorMessage().show(error, code);
        });
  }

  getPostsOfCategories({required var category}) {
    status.value = RequestStatus.LOADING;
    PostProvider().getPostsOfCategory(
        category: category,
        page: page,
        beforeSend: () {},
        onSuccess: (data) {
          if (data.statusCode == 200) {
            List responseBody = data.data;
            postsOfCategoryList.value =
                responseBody.map((e) => PostModel.fromJson(e)).toList();
            status.value = RequestStatus.LOADED;
          } else {
            status.value = RequestStatus.ERROR;
            errorMessage.value = data.statusMessage!;
           // ErrorMessage().show(data.statusMessage!, data.statusCode!);
          }
        },
        onError: (error, code) {
          status.value = RequestStatus.ERROR;
          errorMessage.value = error;

         // ErrorMessage().show(error, code);
        });
  }

}