/// Generated by Flutter GetX Starter on 2022-04-25 20:54
import 'package:get/get.dart';
import 'package:news/local/db/app_db.dart';
import 'package:news/util/request_status.dart';

class PostDetailLogic extends GetxController {
  late AppDb _appDb;
  var status = RequestStatus.INITIALIZE.obs;

  @override
  void onInit() {
    _appDb = AppDb();
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }

  insertFavorite(FavoriteCompanion entity, Function isFavorite) {
    _appDb.insertFavorite(entity).then((value) {
      switch (value) {
        case 1:
          status.value = RequestStatus.SUCCESS;
          isFavorite(true);
          break;
        case 0:
          status.value = RequestStatus.FAILED;
          isFavorite(false);

          break;
        default:
          isFavorite(false);
          break;
      }
    });
  }


  deleteFavorite(int id, Function isFavorite) {
    _appDb.deleteFavorite(id).then((value) {
      switch (value) {
        case 1:
          status.value = RequestStatus.SUCCESS;
          isFavorite(false);
          break;
        case 0:
          status.value = RequestStatus.FAILED;
          isFavorite(true);

          break;
        default:
          isFavorite(true);
          break;
      }
    });
  }
}